# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "walter-dev"
client_id = ""
application_url = "https://localhost"
embedded = false

[access_scopes]
scopes = "read_orders,write_orders,write_products,read_customers,write_draft_orders"

[auth]
redirect_urls = [ "https://localhost/health" ]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["orders/paid"]
  uri = "/webhooks/orders-paid"

  [[webhooks.subscriptions]]
  topics = ["orders/cancelled"]
  uri = "/webhooks/orders-cancelled"

  [[webhooks.subscriptions]]
  topics = ["refunds/create"]
  uri = "/webhooks/refunds-create"

[build]
automatically_update_urls_on_dev = true
